#!/bin/bash

if [ `uname` == Darwin ]; then
  prefix=$(pwd)/app/PretextView.app
  bindir=Contents/MacOS
else
  prefix=$(pwd)/app
  bindir=./
fi

mkdir -p app
cat > "app/.gitignore" <<END
*
END

if [ `uname` == Darwin ]; then
  [ -d app/PretextView.app ] && rm -rf app/PretextView.app
fi

env CC=clang CXX=clang meson setup --buildtype=release --prefix=$prefix --bindir=$bindir --unity on builddir
meson compile -C builddir
meson install -C builddir

